# Conexao com o banco de dados - producao
spring.datasource.url=jdbc:postgresql://localhost:5433/sosysters
spring.datasource.username=admin
spring.datasource.password=sosysterspasswd@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Mail sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pablohsouzacarmo@gmail.com
spring.mail.password=obmp unzj xsvd sucg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Proxy Reverso - respeitar headers de forwarding para HTTPS
server.tomcat.remoteip.remote-ip-header=X-Forwarded-For
server.tomcat.remoteip.protocol-header=X-Forwarded-Proto
server.tomcat.remoteip.protocol-header-value=https
